apiVersion: v1
description: 'Stash by AppsCode - Backup your Kubernetes Volumes'
name: stash
version: v0.10.0-alpha.0
appVersion: v0.10.0-alpha.0
home: https://appscode.com/products/stash/
icon: https://cdn.appscode.com/images/products/stash/icons/android-icon-192x192.png
sources:
- https://github.com/stashed/stash
maintainers:
- name: appscode
  email: support@appscode.com
