apiVersion: v1
description: Enterprise features for Stash by AppsCode
name: stash-enterprise
version: v0.25.0
appVersion: v0.25.0
home: https://stash.run
icon: https://cdn.appscode.com/images/products/stash/stash-enterprise-icon.png
sources:
- https://github.com/stashed
maintainers:
- name: appscode
  email: support@appscode.com
