project:
  name: Stash Enterprise by AppsCode
  shortName: Stash Enterprise
  url: https://github.com/stashed/stash
  description: Enterprise features for Stash by AppsCode
  app: a Stash Enterprise operator
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: stash-enterprise
  values: "-- generate from values file --"
  valuesExample: "-- generate from values file --"
prerequisites:
- Kubernetes 1.11+
release:
  name: stash-enterprise
  namespace: kube-system
