apiVersion: v2
name: stash-crds
description: Stash Custom Resource Definitions
type: application
version: v2021.04.12
appVersion: v2021.04.12
home: https://stash.run
icon: https://cdn.appscode.com/images/products/stash/stash-icon.png
sources:
- https://github.com/stashed
maintainers:
- name: appscode
  email: support@appscode.com
