apiVersion: v2
name: stash-ui-server
description: A Helm chart for stash-ui-server by AppsCode
type: application
version: v0.12.0
appVersion: v0.12.0
home: https://github.com/stashed/stash-ui-server
icon: https://cdn.appscode.com/images/products/stash/stash-community-icon.png
sources:
- https://github.com/stashed/stash-ui-server
maintainers:
- name: appscode
  email: support@appscode.com
