{{ if .Values.elasticsearch.enabled }}
apiVersion: stash.appscode.com/v1beta1
kind: Function
metadata:
  name: 'elasticsearch-backup-6.3.0'
  labels:
    {{- include "stash-catalog.labels" . | nindent 4 }}
spec:
  args:
  - backup-es
  - --provider=${REPOSITORY_PROVIDER:=}
  - --bucket=${REPOSITORY_BUCKET:=}
  - --endpoint=${REPOSITORY_ENDPOINT:=}
  - --region=${REPOSITORY_REGION:=}
  - --path=${REPOSITORY_PREFIX:=}
  - --secret-dir=/etc/repository/secret
  - --scratch-dir=/tmp
  - --enable-cache=${ENABLE_CACHE:=true}
  - --max-connections=${MAX_CONNECTIONS:=0}
  - --wait-timeout=${waitTimeout:={{ .Values.waitTimeout}}}
  - --hostname=${HOSTNAME:=}
  - --interim-data-dir=${INTERIM_DATA_DIR}
  - --namespace=${NAMESPACE:=default}
  - --appbinding=${TARGET_NAME:=}
  - --backupsession=${BACKUP_SESSION:=}
  - --es-args=${args:={{ .Values.elasticsearch.backup.args }}}
  - --retention-keep-last=${RETENTION_KEEP_LAST:=0}
  - --retention-keep-hourly=${RETENTION_KEEP_HOURLY:=0}
  - --retention-keep-daily=${RETENTION_KEEP_DAILY:=0}
  - --retention-keep-weekly=${RETENTION_KEEP_WEEKLY:=0}
  - --retention-keep-monthly=${RETENTION_KEEP_MONTHLY:=0}
  - --retention-keep-yearly=${RETENTION_KEEP_YEARLY:=0}
  - --retention-keep-tags=${RETENTION_KEEP_TAGS:=}
  - --retention-prune=${RETENTION_PRUNE:=false}
  - --retention-dry-run=${RETENTION_DRY_RUN:=false}
  - --output-dir=${outputDir:=}
  - --license-apiservice=${LICENSE_APISERVICE:=}
  image: '{{ include "catalog.registry" . }}/stash-elasticsearch:6.3.0-v14'
  volumeMounts:
  - mountPath: /etc/repository/secret
    name: ${secretVolume}
{{ end }}
