apiVersion: v1
description: 'Free community features for Stash by AppsCode'
name: stash-community
version: v0.14.1
appVersion: v0.14.1
home: https://stash.run
icon: https://cdn.appscode.com/images/products/stash/stash-community-icon.png
sources:
- https://github.com/stashed
maintainers:
- name: appscode
  email: support@appscode.com
