{{ if .Values.postgres.enabled }}
apiVersion: stash.appscode.com/v1beta1
kind: Task
metadata:
  name: 'postgres-restore-12.4'
  labels:
    {{- include "stash-catalog.labels" . | nindent 4 }}
spec:
  steps:
  - name: postgres-restore-12.4
    params:
    - name: outputDir
      value: /tmp/output
    - name: secretVolume
      value: secret-volume
  - name: update-status
    params:
    - name: outputDir
      value: /tmp/output
    - name: secretVolume
      value: secret-volume
  volumes:
  - name: secret-volume
    secret:
      secretName: ${REPOSITORY_SECRET_NAME}
{{ end }}
