{{- if eq "true" ( include "cleaner.generate" . ) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "stash-community.fullname" . }}-cleaner
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stash-community.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 120
  template:
    spec:
      {{- include "appscode.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "stash-community.serviceAccountName" . }}
      containers:
      - name: busybox
        image: {{ include "cleaner.registry" . }}/{{ .Values.cleaner.repository }}:{{ .Values.cleaner.tag }}
        command:
          - sh
          - -c
          - "sleep 2; \
           kubectl delete validatingwebhookconfigurations admission.stash.appscode.com || true;      \
           kubectl delete mutatingwebhookconfiguration admission.stash.appscode.com || true;         \
           kubectl delete validatingwebhookconfigurations admission.stash.appscode.com || true;      \
           kubectl delete mutatingwebhookconfiguration admission.stash.appscode.com || true;         \
           kubectl delete apiservice v1alpha1.admission.stash.appscode.com || true;                  \
           kubectl delete apiservice v1alpha1.repositories.stash.appscode.com || true;               \
           kubectl delete apiservice v1alpha1.stash.appscode.com || true;                            \
           kubectl delete apiservice v1beta1.admission.stash.appscode.com || true;                   \
           kubectl delete functions.stash.appscode.com update-status pvc-backup pvc-restore || true; \
           kubectl delete tasks.stash.appscode.com pvc-backup pvc-restore || true;"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
      restartPolicy: Never
{{ end }}
