{{ if .Values.mongodb.enabled }}
apiVersion: stash.appscode.com/v1beta1
kind: Function
metadata:
  name: 'mongodb-restore-4.4.6'
  labels:
    {{- include "stash-catalog.labels" . | nindent 4 }}
spec:
  args:
  - restore-mongo
  - --provider=${REPOSITORY_PROVIDER:=}
  - --bucket=${REPOSITORY_BUCKET:=}
  - --endpoint=${REPOSITORY_ENDPOINT:=}
  - --insecure-tls=${REPOSITORY_INSECURE_TLS:=}
  - --region=${REPOSITORY_REGION:=}
  - --path=${REPOSITORY_PREFIX:=}
  - --storage-secret-name=${REPOSITORY_SECRET_NAME:=}
  - --storage-secret-namespace=${REPOSITORY_SECRET_NAMESPACE:=}
  - --scratch-dir=/stash-tmp
  - --enable-cache=false
  - --max-connections=${MAX_CONNECTIONS:=0}
  - --hostname=${HOSTNAME:=}
  - --source-hostname=${SOURCE_HOSTNAME:=}
  - --mongo-args=${args:={{ .Values.mongodb.restore.args }}}
  - --max-concurrency=${MAX_CONCURRENCY:={{ .Values.mongodb.maxConcurrency}}}
  - --wait-timeout=${waitTimeout:={{ .Values.waitTimeout}}}
  - --namespace=${NAMESPACE:=default}
  - --appbinding=${TARGET_NAME:=}
  - --appbinding-namespace=${TARGET_NAMESPACE:=}
  - --restoresession=${RESTORE_SESSION:=}
  - --snapshot=${RESTORE_SNAPSHOTS:=}
  - --output-dir=${outputDir:=}
  - --license-apiservice=${LICENSE_APISERVICE:=}
  - --authentication-database=${authenticationDatabase:=admin}
  image: '{{ include "catalog.registry" (merge (dict "_reg" "ghcr.io" "_repo" "stashed")
    .Values) }}/stash-mongodb:4.4.6-v27'
{{ end }}
